services:
  - type: static_site
    name: portfolio
    env: node
    branch: main
    buildCommand: npm run build
    publishCommand: npm run build
    publishPath: dist
    plan: free
    headers:
      - path: /spline/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
